name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - ipywidgets
  - git
  - numpy
  - matplotlib
  - pip
  - pip:
      - $LITHOPS
      - click
      - s3fs
      - rich
      - pandas
      - seaborn

